### ISSUE TITLE
feature: add cellforrow to the delegate

### ISSUE THREAD

**Issue by FreudGit** [LaurentiuUngur/LUAutocompleteView#3]
Hi.

I want to use a full custom TableViewCell, and be able to set some fields.

So, ideally, I need  a delegate for cellForRowAt  :)

Thanks!

**Comment by LaurentiuUngur** [comment]
You can have custom table view cells. Please take a look here https://github.com/LaurentiuUngur/LUAutocompleteView#customisation

**Comment by FreudGit** [comment]
Hi Thanks, but I need to be able to have many UILabel and be able to set the text for all.

At this time, because to access to cellForRowAt, there are no way to modify custom labels, no?

**Comment by LaurentiuUngur** [comment]
Well you could do a workaround. Since `override func set(text: String)` has as parameter just one string not many, you could concatenate your strings for labels and use some separator so you can separate them in the cell then set your labels. E.g: If you have 3 labels in the same cell and what to set "one", "two", "three" as text, you could concatenate those ("one•two•three)", the in `override func set(text: String)` you just have to separate the `text`.

**Comment by FreudGit** [comment]
Yeah, thanks.

A delegate for cellForRowAt can be a good idea for a future release.  Anyway, thanks for your support and have a great day!
